# Generated by Django 4.0.4 on 2022-06-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_date_auctionlisting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
