# Generated by Django 4.0.4 on 2022-06-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='time',
        ),
    ]
