# Generated by Django 4.0.4 on 2022-06-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='status',
            new_name='flActive',
        ),
    ]
